SilphCo_4F_Text_CantYouSeeImHiding::
    .string "Sssh!\n"
    .string "Can't you see I'm hiding?$"

SilphCo_4F_Text_TeamRocketIsGone::
    .string "Huh?\n"
    .string "TEAM ROCKET is gone?$"

SilphCo_4F_Text_GruntJulianIntro::
    .string "TEAM ROCKET has taken control\n"
    .string "of SILPH CO.!$"

SilphCo_4F_Text_GruntJulianDefeat::
    .string "Arrgh!$"

SilphCo_4F_Text_GruntJulianPostBattle::
    .string "Fwahahaha!\n"
    .string "My BOSS has been after this place!$"

SilphCo_4F_Text_RodneyIntro::
    .string "My POKéMON is my loyal servant.$"

SilphCo_4F_Text_RodneyDefeat::
    .string "Darn!\n"
    .string "You weak POKéMON!$"

SilphCo_4F_Text_RodneyPostBattle::
    .string "The doors are electronically\n"
    .string "locked.\p"
    .string "It takes a CARD KEY to open the\n"
    .string "doors here.$"

SilphCo_4F_Text_GruntCallumIntro::
    .string "Intruder spotted!$"

SilphCo_4F_Text_GruntCallumDefeat::
    .string "Who are you?$"

SilphCo_4F_Text_GruntCallumPostBattle::
    .string "I better tell the BOSS on 11F!$"

SilphCo_4F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "4F$"

