CeladonCity_Condominiums_1F_Text_Meowth::
    .string "MEOWTH: Meow!$"

CeladonCity_Condominiums_1F_Text_SendPlayerToGetTeaLeaves::
    .string "Oh, it's just wonderful.\p"
    .string "Somebody finally managed to get rid\n"
    .string "of TEAM ROCKET\p"
    .string "I will now able to get TEA LEAVES\n"
    .string "from Erika again.\p"
    .string "Would you be a dear and pick up my\n"
    .string "order of TEA LEAVES from her?\p"
    .string "She should be at her GYM right now,\n"
    .string "ready to face new challengers.$"

CeladonCity_Condominiums_1F_Text_PlayerDoesNotHaveTeaLeaves::
    .string "Did you manage to get the TEA LEAVES\n"
    .string "from Erika, sweetheart?\p"
    .string "She should be at her GYM right now,\n"
    .string "ready to face new challengers.$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "Did you manage to get the TEA LEAVES\n"
    .string "from Erika, sweetheart?\p"
    .string "Oh, you have them!\p"
    .string "I'll make you a cup right away.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "Nothing beats thirst like some hot\n"
    .string "TEA.\p"
    .string "It really is the best.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .string "My dear POKéMON keep me company.\n"
    .string "MEOWTH even brings money home!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .string "Oh, hello, dearie.\n"
    .string "Did you enjoy my TEA?\p"
    .string "By the way, dear. Are you, by any\n"
    .string "chance, from PALLET TOWN?\p"
    .string "A girl from PALLET TOWN, DAISY,\n"
    .string "she enjoys TEA every day.\p"
    .string "She visits the CELADON DEPT. STORE\n"
    .string "to buy some TEA.$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "CLEFAIRY: Pi pippippi!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "NIDORAN♀: Kya kyaoo!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .string "CELADON MANSION\n"
    .string "Manager's Suite$"

CeladonCity_Condominiums_1F_Text_TeaWomanBeforeGiovanniIsBeaten::
    .string "I'm deeply sorry, dear.\p"
    .string "Normally I would have a nice cup\n"
    .string "of TEA for you, but I'm fresh out.\p"
    .string "The problem is that I usually get my\n"
    .string "TEA LEAVES from Erika.\p"
    .string "She's not just a talented GYM LEADER\n"
    .string "you know.\p"
    .string "She does so much more for the people\n"
    .string "of this town.\p"
    .string "Sadly I can't get any more TEA\n"
    .string "LEAVES from her.\p"
    .string "At least not until that TEAM ROCKET\n"
    .string "is dealt with.$"
