Route5_Text_UndergroundPathSign::
    .string "UNDERGROUND PATH\n"
    .string "CERULEAN CITY - VERMILION CITY$"

Route5_Text_ThomasIntro::
    .string "I've been runningn up and down\n"
    .string "for 5 hours.$"

Route5_Text_ThomasDefeat::
    .string "My cousin has much cooler\n"
    .string "POKéMON than you.$"

Route5_Text_ThomasPostBattle::
    .string "Did you know you can trade\n"
    .string "POKéMON?$"
