SafariZone_SecretHouse_Text_CongratsYouveWon::
    .string "Ah! Finally!\p"
    .string "You're the first person to reach\n"
    .string "the SECRET HOUSE!\p"
    .string "Although I made a campaign\n"
    .string "for our grand opening,\p"
    .string "I was getting worried that no one\n"
    .string "would win our campaign prize.\p"
    .string "Congratulations!\n"
    .string "You have won!$"

SafariZone_SecretHouse_Text_ReceivedHM03FromAttendant::
    .string "{PLAYER} received HM03\n"
    .string "from the attendant!$"

SafariZone_SecretHouse_Text_ExplainSurf::
    .string "HM03 is SURF.\p"
    .string "POKéMON will be able to ferry you\n"
    .string "across water using it.\p"
    .string "What's that?\p"
    .string "You don't want to use HMs on your\n"
    .string "own POKéMON?\p"
    .string "Okay well, maybe someone will gift\n"
    .string "you a LAPRAS or something, I dunno.$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize::
    .string "You don't have room for this\n"
    .string "fabulous prize!$"

