Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .string "Many POKéMON live only in forests \n"
    .string "and caves.\p"
    .string "You need to be persistent and look\n"
    .string "everywhere to get different kinds.$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .string "Have you noticed the skinny trees\n"
    .string "on the roadside?\p"
    .string "They can be cut down by a special\n"
    .string "POKéMON move, I hear.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .string "Do you know the evolution-cancel\n"
    .string "technique?\p"
    .string "When a POKéMON is evolving, you\n"
    .string "can stop the process.\p"
    .string "It's a technique for raising\n"
    .string "POKéMON the way they are.$"

Route2_ViridianForest_NorthEntrance_Text_BugsyGreeting::
    .string "???: Hey, have you seen my BUG\n"
    .string "NET?\p"
    .string "I left it somewhere around here,\n"
    .string "but I can't find it anywhere.\p"
    .string "Oh, you're a POKéMON TRAINER?\n"
    .string "So am I! My name's BUGSY.\p"
    .string "Sorry, I can't battle you right now.\n"
    .string "I came to Kanto to catch cool\p"
    .string "BUG POKéMON.\p"
    .string "If you help me find my NET I promise\n"
    .string "to battle you some day.\p"
    .string "Follow me!$"

