SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
    .string "CAPTAIN: Ooargh…\n"
    .string "I feel hideous…\l"
    .string "Urrp! Seasick…$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
    .string "{PLAYER} rubbed the CAPTAIN's\n"
    .string "back!\p"
    .string "Rub-rub…\n"
    .string "Rub-rub…$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
    .string "CAPTAIN: Whew! Thank you!\n"
    .string "I'm feeling much better now.\p"
    .string "You want to see my hidden CUT\n"
    .string "technique?\p"
    .string "You can have this! The HIDDEN\n"
    .string "MACHINE for CUT!\p"
    .string "My FARFETCH'D is already a\n"
    .string "master at cutting down trees.\p"
    .string "Teach CUT to your POKéMON, and\n"
    .string "you can see it CUT anytime!\p"
    .string "Or just call on my FARFETCH'D if\n"
    .string "you ever need to chop down a tree.$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .string "{PLAYER} obtained HM01\n"
    .string "from the CAPTAIN!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
    .string "Why not try it with the trees\n"
    .string "around VERMILION CITY?$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .string "CAPTAIN: …Whew!\p"
    .string "Now that I'm not sick anymore,\n"
    .string "I guess it's time.\p"
    .string "The S.S. ANNE will set sail soon!\p"
    .string "Farewell, until our return to\n"
    .string "VERMILION CITY!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
    .string "Oh, no!\n"
    .string "You have no room for this!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .string "Yuck!\n"
    .string "Shouldn't have looked!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
    .string "How to Conquer Seasickness…\n"
    .string "The CAPTAIN's reading this!$"

SSAnne_CaptainsOffice_Text_Farfetchd::
    .string "FARFETCH'D: Ch-ding!$"
