Text_FoundALetter::
    .string "There's a letter…\n"
    .string "It's addressed to me…$"

Text_FoundAnotherLetter::
    .string "It's another letter…$"

Text_First_Letter::
    .string "Hello, {PLAYER}.\p"
    .string "Were you expecting to find\n"
    .string "something here?\p"
    .string "It seems you're too late…$"

Text_Second_Letter::
    .string "{PLAYER}!\p"
    .string "It seems you've found another\n"
    .string "one of my letters.\p"
    .string "I wonder how that makes you\n"
    .string "feel?$"

Text_Third_Letter::
    .string "{PLAYER}, {PLAYER}, {PLAYER}…\p"
    .string "You must be getting\n"
    .string "frustrated by now…\p"
    .string "Don't worry. We'll meet\n"
    .string "soon enough.$"
