gOtherText_NewName::
    .string "NEW NAME$"

gNameChoice_Blue::
    .string "BLUE$"

gNameChoice_Green::
    .string "GREEN$"

gNameChoice_Red::
    .string "RED$"

gNameChoice_Leaf::
    .string "LEAF$"

gNameChoice_Fire::
    .string "FIRE$"

gNameChoice_Gary::
    .string "GARY$"

gNameChoice_Kaz::
    .string "KAZ$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Ash::
    .string "GARY$"

gNameChoice_Kene::
    .string "KENE$"

gNameChoice_Geki::
    .string "GEKI$"

gNameChoice_Jak::
    .string "JAK$"

gNameChoice_Janne::
    .string "JANNE$"

gNameChoice_Jonn::
    .string "JONN$"

gNameChoice_Kamon::
    .string "KAMON$"

gNameChoice_Karl::
    .string "KARL$"

gNameChoice_Taylor::
    .string "TAYLOR$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "HIRO$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JON$"

gNameChoice_Ralph::
    .string "RALPH$"

gNameChoice_Kay::
    .string "KAY$"

gNameChoice_Tosh::
    .string "TOSH$"

gNameChoice_Roak::
    .string "ROAK$"

gNameChoice_Omi::
    .string "OMI$"

gNameChoice_Jodi::
    .string "JODI$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "HILLARY$"

gNameChoice_Makey::
    .string "MAKEY$"

gNameChoice_Michi::
    .string "MICHI$"

gNameChoice_Paula::
    .string "PAULA$"

gNameChoice_June::
    .string "JUNE$"

gNameChoice_Cassie::
    .string "CASSIE$"

gNameChoice_Rey::
    .string "REY$"

gNameChoice_Seda::
    .string "SEDA$"

gNameChoice_Kiko::
    .string "KIKO$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "NORIE$"

gNameChoice_Sai::
    .string "SAI$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
    .string "The various buttons will be explained in\n"
    .string "the order of their importance.$"

gControlsGuide_Text_DPad::
    .string "Moves the main character.\n"
    .string "Also used to choose various data\n"
    .string "headings.$"

gControlsGuide_Text_AButton::
    .string "Used to confirm a choice, check\n"
    .string "things, chat, and scroll text.$"

gControlsGuide_Text_BButton::
    .string "Used to exit, cancel a choice,\n"
    .string "and cancel a mode.$"

gControlsGuide_Text_StartButton::
    .string "Press this button to open the\n"
    .string "MENU.$"

gControlsGuide_Text_SelectButton::
    .string "Used to shift items and to use\n"
    .string "a registered item.$"

gControlsGuide_Text_LRButtons::
    .string "The LR buttons can be used to\n"
    .string "switch around POKéMON, or to\n"
    .string "FLY (L) and Repel (R).$"

gOakSpeech_Text_AskPlayerGender::
    .string "Now tell me. Are you a boy?\n"
    .string "Or are you a girl?$"

gPikachuIntro_Text_Page1::
    .string "This version of POKéMON Fire Red has\n"
    .string "an increased variety of mons from\n"
    .string "the first 3 generations.\n"
    .string "\n"
    .string "This is not intended to be a high-\n"
    .string "difficulty ROM hack, though it is \n"
    .string "significantly harder than the vanilla\n"
    .string "version of Fire Red.$"

gPikachuIntro_Text_Page2::
    .string "My intention is to eventually include\n"
    .string "mons up until gen V, but this is still\n"
    .string "just a DEMO of what is to be.\n"
    .string "\n"
    .string "Many QoL updates are included in the\n"
    .string "current DEMO already, along with some\n"
    .string "unique new features.$"

gPikachuIntro_Text_Page3::
    .string "HMs do not need to be taught to any\n"
    .string "of your POKéMON.\n"
    .string "\n"
    .string "For more insight into the changes\n"
    .string "made in this ROM hack, consult\n"
    .string "the accompanying documentation.\n"
    .string "\n"
    .string "Press A to continue.$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "Hello, there!\n"
    .string "Glad to meet you!\p"
    .string "Welcome to the world of POKéMON!\p"
    .string "My name is PROFESSOR OAK.\p$"

gOakSpeech_Text_ThisWorld::
    .string "This world…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "…is inhabited far and wide by\n"
    .string "creatures called POKéMON.\p$"

gOakSpeech_Text_IStudyPokemon::
    .string "For some people, POKéMON are pets.\n"
    .string "Others use them for battling.\p"
    .string "As for myself…\p"
    .string "I study POKéMON as a profession.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "But first, tell me a little about\n"
    .string "yourself.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Let's begin with your name.\n"
    .string "What is it?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Right…\n"
    .string "So your name is {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
    .string "This is my grandson.\p"
    .string "He's been your rival since you both\n"
    .string "were babies.\p"
    .string "…Erm, what was his name now?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "Your rival's name, what was it now?$"

gOakSpeech_Text_ConfirmRivalName::
    .string "…Er, was it {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
    .string "That's right! I remember now!\n"
    .string "His name is {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "Your very own POKéMON legend is\n"
    .string "about to unfold!\p"
    .string "A world of dreams and adventures\n"
    .string "with POKéMON awaits! Let's go!$"
