Route7_Text_UndergroundPathSign::
    .string "UNDERGROUND PATH\n"
    .string "CELADON CITY - LAVENDER TOWN$"

Route7_Text_Jessie1::
    .string "JESSIE: What do you mean you\n"
    .string "don't know which CITY we are\l"
    .string "stationed in?$"

Route7_Text_James1::
    .string "JAMES: I told you… the BOSS has\n"
    .string "plans in both CELADON CITY and\l"
    .string "SAFFRON CITY.\p"
    .string "I say we just flip a coin.\p"
    .string "HEADS we go left to the SECRET\n"
    .string "HIDEOUT, TAILS we go right to\l"
    .string "SILPH CO.$"

Route7_Text_Jessie2::
    .string "JESSIE: Ugh! Is that the best\n"
    .string "you oafs can come up with…?$"

Route7_Text_Meowth1::
    .string "MEOWTH: HEY! Oafs? Plural?\p"
    .string "I'm not the one who blasted us into\n"
    .string "the sky during our last mission.$"

Route7_Text_James2::
    .string "JAMES: That was not my fault!\p"
    .string "How was I supposed to know that\n"
    .string "ELECTRODE would use SELF-DESTRUCT?$"

Route7_Text_Meowth2::
    .string "MEOWTH: Have you never heard of\n"
    .string "a POKéDEX before, you moron?$"

Route7_Text_Jessie3::
    .string "JESSIE: Hey geniuses, somebody is\n"
    .string "listening in on our top-secret\l"
    .string "conversation.$"

Route7_Text_James3::
    .string "JAMES: Huh…?$"

Route7_Text_James4::
    .string "Stop listening in on us, kid!\p"
    .string "This is highly sensitive information\n"
    .string "that we're discussing here.$"

Route7_Text_Meowth3::
    .string "MEOWTH: Yeah! How about you make\n"
    .string "like a PIKA and SHOO…$"

Route7_Text_James5::
    .string "JAMES: HA! Good one, MEOWTH.$"

Route7_Text_Jessie4::
    .string "JESSIE: Oh, will you idiots stop\n"
    .string "talking already?$"

Route7_Text_Jessie5::
    .string "And you…\p"
    .string "Get lost, kid. Before we take your\n"
    .string "POKéMON from you.$"

PewterCity_Text_JamesPostScene::
    .string "Don't start thinking you can get\n"
    .string "any more info out of me, kid.$"

PewterCity_Text_JessiePostScene::
    .string "Beat it, twerp!$"
