RocketHideout_B1F_Text_GruntGavinIntro::
    .string "Who are you?\n"
    .string "How did you get here?$"

RocketHideout_B1F_Text_GruntGavinDefeat::
    .string "Oww!\n"
    .string "Beaten!$"

RocketHideout_B1F_Text_GruntGavinPostBattle::
    .string "Blast it… You're dissing TEAM\n"
    .string "ROCKET, aren't you?$"

RocketHideout_B1F_Text_GruntRonanIntro::
    .string "You broke into TEAM ROCKET's\n"
    .string "operation? What nerve!$"

RocketHideout_B1F_Text_GruntRonanDefeat::
    .string "Boom!$"

RocketHideout_B1F_Text_GruntRonanPostBattle::
    .string "You're not going to get away with\n"
    .string "this, brat!$"

RocketHideout_B1F_Text_GruntDorianIntro::
    .string "Intruder alert!$"

RocketHideout_B1F_Text_GruntDorianDefeat::
    .string "I can't do it!$"

RocketHideout_B1F_Text_GruntDorianPostBattle::
    .string "SILPH SCOPE? Humph!\n"
    .string "I don't know where it is.$"

RocketHideout_B1F_Text_GruntCliveIntro::
    .string "Why did you come here?$"

RocketHideout_B1F_Text_GruntCliveDefeat::
    .string "This won't do!$"

RocketHideout_B1F_Text_GruntClivePostBattle::
    .string "Okay, I'll talk…\n"
    .string "Take the elevator to see my BOSS.$"

RocketHideout_B1F_Text_GruntDariusIntro::
    .string "Are you lost, you little mouse?$"

RocketHideout_B1F_Text_GruntDariusDefeat::
    .string "Why…?$"

RocketHideout_B1F_Text_GruntDariusPostBattle::
    .string "Uh-oh, that ruckus somehow opened\n"
    .string "the door!$"

