MtMoon_B2F_Text_MiguelIntro::
    .string "Hey, stop!\p"
    .string "I found these fossils!\n"
    .string "They're both mine!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "Okay!\n"
    .string "I'll share!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "We'll each take a fossil!\n"
    .string "No being greedy!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "All right.\n"
    .string "Then this fossil is mine!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "Far away, on CINNABAR ISLAND,\n"
    .string "there's a POKéMON LAB.\p"
    .string "They do research on regenerating\n"
    .string "fossils.$"

MtMoon_B2F_Text_GruntKeiranIntro::
    .string "We, TEAM ROCKET, shall find the\n"
    .string "fossils!\p"
    .string "Reviving POKéMON from them will\n"
    .string "earn us huge riches!$"

MtMoon_B2F_Text_GruntKeiranDefeat::
    .string "Urgh!\n"
    .string "Now I'm mad!$"

MtMoon_B2F_Text_GruntKeiranPostBattle::
    .string "You made me mad!\n"
    .string "TEAM ROCKET will blacklist you!$"

MtMoon_B2F_Text_GruntLarsIntro::
    .string "We, TEAM ROCKET, are POKéMON\n"
    .string "gangsters!\l"
    .string "We strike fear with our strength!$"

MtMoon_B2F_Text_GruntLarsDefeat::
    .string "I blew it!$"

MtMoon_B2F_Text_GruntLarsPostBattle::
    .string "Darn it all!\n"
    .string "My associates won't stand for this!$"

MtMoon_B2F_Text_GruntCalebIntro::
    .string "We're pulling a big job here!\n"
    .string "Get lost, kid!$"

MtMoon_B2F_Text_GruntCalebDefeat::
    .string "So, you are good…$"

MtMoon_B2F_Text_GruntCalebPostBattle::
    .string "If you find a fossil, give it to me\n"
    .string "and scram!$"

MtMoon_B2F_Text_GruntKellanIntro::
    .string "Little kids shouldn't be messing\n"
    .string "around with grown-ups!\p"
    .string "It could be bad news!$"

MtMoon_B2F_Text_GruntKellanDefeat::
    .string "I'm steamed!$"

MtMoon_B2F_Text_GruntKellanPostBattle::
    .string "POKéMON lived here long before\n"
    .string "people came.$"

MtMoon_B2F_Text_YouWantDomeFossil::
    .string "Do you want the DOME FOSSIL?$"

MtMoon_B2F_Text_YouWantHelixFossil::
    .string "Do you want the HELIX FOSSIL?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
    .string "Obtained the HELIX FOSSIL!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
    .string "Obtained the DOME FOSSIL!$"

