FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .string "Uh…\n"
    .string "Oh, yes, I'm the MOVE DELETER.\p"
    .string "I can make POKéMON forget their\n"
    .string "moves.\p"
    .string "Would you like me to do that?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
    .string "Which POKéMON should forget a\n"
    .string "move?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
    .string "Which move should be forgotten?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
    .string "{STR_VAR_1} seems to know only one\n"
    .string "move…$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
    .string "Hm! {STR_VAR_1}'s {STR_VAR_2}?\n"
    .string "That move should be forgotten?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
    .string "It worked to perfection!\p"
    .string "{STR_VAR_1} has forgotten\n"
    .string "{STR_VAR_2} completely.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
    .string "Come again if there are other\n"
    .string "moves to be forgotten.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
    .string "What?\n"
    .string "No EGG should know any moves.$"

FuchsiaCity_House3_Text_EggMoveTutorIntro::
    .string "Did you know POKéMON can only learn\n"
    .string "certain moves from their parents?\p"
    .string "At least… that's what we believed\n"
    .string "before my most recent research.\p"
    .string "Turns out you can teach EGG MOVES\n"
    .string "to POKéMON with the right method.\p"
    .string "I'll do it for you in exchange for\n"
    .string "a HEART SCALE.$"

FuchsiaCity_House3_Text_EggMoveTutorAskTeach::
    .string "Want me to teach an EGG MOVE\n"
    .string "to one of your POKeMON?$"

FuchsiaCity_House3_Text_EggMoveTutorChooseMon::
    .string "Which POKeMON should I tutor?$"

FuchsiaCity_House3_Text_EggMoveTutorChooseMove::
    .string "Which move should I teach?$"

FuchsiaCity_House3_Text_EggMoveTutorNoMoves::
    .string "Sorry…\p"
    .string "It doesn't look like I can teach\n"
    .string "that POKeMON an EGG MOVE.$"

FuchsiaCity_House3_Text_EggMoveTutorCantTeachEgg::
    .string "I can't teach moves to an EGG.$"

FuchsiaCity_House3_Text_EggMoveTutorNeedHeartScale::
    .string "I'll need one HEART SCALE for\n"
    .string "each move I teach.$"

FuchsiaCity_House3_Text_EggMoveTutorHandedHeartScale::
    .string "{PLAYER} handed over one\n"
    .string "HEART SCALE in exchange.$"

FuchsiaCity_House3_Text_EggMoveTutorComeAgain::
    .string "Come again.$"
