Route12_FishingHouse_Text_DoesPlayerHaveProperFishingGear::
    .string "I'm the FISHING GURU's younger\n"
    .string "brother.\p"
    .string "I specialize in MAGIKARP. I'm looking\n"
    .string "somebody who has the biggest one.\p"
    .string "Do you have proper fishing gear?$"

Route12_FishingHouse_Text_UsingGoodRod::
    .string "Hmm, it looks like you're still using\n"
    .string "your GOOD ROD. That won't do.$"

Route12_FishingHouse_Text_UsingOldRod::
    .string "Hmm, it looks like you're still using\n"
    .string "an OLD ROD. That won't do.$"

Route12_FishingHouse_Text_VisitMyOldestBrother::
    .string "I have another brother who lives\n"
    .string "in FUCHSIA CITY. You should visit\l"
    .string "him some time.$"

Route12_FishingHouse_Text_CatchABigMagikarpForMe::
    .string "Great! You came prepared.\p"
    .string "From the seas to rivers, go out\n"
    .string "and land the big one, my friend.\p"
    .string "Now, I have a request.\p"
    .string "If you catch a big MAGIKARP \n"
    .string "with that ROD, I want to see it.\p"
    .string "As much as I love to fish, I also\n"
    .string "love seeing gigantic MAGIKARP.$"

Route12_FishingHouse_Text_TryFishingBringMeMagikarp::
    .string "Hello there, {PLAYER}!\n"
    .string "Have you been fishing?\p"
    .string "Try fishing with the SUPER ROD in\n"
    .string "any body of water.\p"
    .string "You'll find different POKéMON in\n"
    .string "different places.\p"
    .string "Oh, and don't forget to bring me\n"
    .string "gigantic MAGIKARP.$"

Route12_FishingHouse_Text_OhMagikarpAllowMeToSee::
    .string "Oh? {PLAYER}?\n"
    .string "Why, if it isn't a MAGIKARP!\p"
    .string "Allow me to see it, quick!$"

Route12_FishingHouse_Text_WhoaXInchesTakeThis::
    .string "… … …Whoa!\n"
    .string "{STR_VAR_2} inches!\p"
    .string "You have a rare appreciation for\n"
    .string "the fine, poetic aspects of fishing!\p"
    .string "You must take this.\n"
    .string "I insist!$"

Route12_FishingHouse_Text_LookForwardToGreaterRecords::
    .string "I'll look forward to seeing greater\n"
    .string "records from you!$"

Route12_FishingHouse_Text_HuhXInchesSameSizeAsLast::
    .string "Huh?\n"
    .string "{STR_VAR_2} inches?\p"
    .string "This is the same size as the one\n"
    .string "I saw before.$"

Route12_FishingHouse_Text_HmmXInchesDoesntMeasureUp::
    .string "Hmm…\n"
    .string "This one is {STR_VAR_2} inches long.\p"
    .string "It doesn't measure up to the\n"
    .string "{STR_VAR_3}-inch one you brought before.$"

Route12_FishingHouse_Text_DoesntLookLikeMagikarp::
    .string "Uh… That doesn't look much like\n"
    .string "a MAGIKARP.$"

Route12_FishingHouse_Text_NoRoomForGift::
    .string "Oh, no!\p"
    .string "I had a gift for you, but you have\n"
    .string "no room for it.$"

Route12_FishingHouse_Text_MostGiganticMagikarpXInches::
    .string "The most gigantic MAGIKARP\n"
    .string "I have ever witnessed…\p"
    .string "{STR_VAR_3} inches!$"

Route12_FishingHouse_Text_BlankChartOfSomeSort::
    .string "It's a blank chart of some sort.\p"
    .string "It has spaces for writing in\n"
    .string "records of some kind.$"

