RocketHideout_B3F_Text_GruntBeckIntro::
    .string "We're hoarding all the good\n"
    .string "items here.$"

RocketHideout_B3F_Text_GruntBeckDefeat::
    .string "Oof!\n"
    .string "Taken down!$"

RocketHideout_B3F_Text_GruntBeckPostBattle::
    .string "SILPH SCOPE?\n"
    .string "Oh, that machine the BOSS stole.\p"
    .string "It's here somewhere.$"

RocketHideout_B3F_Text_GruntMalcolmIntro::
    .string "We got word from upstairs that you\n"
    .string "were coming!$"

RocketHideout_B3F_Text_GruntMalcolmDefeat::
    .string "What?\n"
    .string "I lost? No!$"

RocketHideout_B3F_Text_GruntMalcolmPostBattle::
    .string "Go ahead and go!\p"
    .string "But you can't run the elevator\n"
    .string "without the LIFT KEY.$"

