VermilionCity_PokemonCenter_1F_Text_TrainerMonsStrongerThanWild::
    .string "Even if they are the same level,\n"
    .string "POKéMON can have very different\l"
    .string "stats and abilities.\p"
    .string "A POKéMON raised by a TRAINER is\n"
    .string "stronger than one in the wild.$"

VermilionCity_PokemonCenter_1F_Text_PoisonedMonFaintedWhileWalking::
    .string "My POKéMON was poisoned!\n"
    .string "It fainted while we were walking!$"

VermilionCity_PokemonCenter_1F_Text_AllMonWeakToSpecificTypes::
    .string "It is true that a higher-level\n"
    .string "POKéMON will be more powerful…\p"
    .string "But, all POKéMON will have weak\n"
    .string "points against specific types.\p"
    .string "So, there appears to be no\n"
    .string "universally strong POKéMON.$"

VermilionCity_PokemonCenter_1F_Text_UrgeToBattleSomeoneAgain::
    .string "The urge to battle with someone\n"
    .string "you've tangled with before…\p"
    .string "Have you ever had that urge?\n"
    .string "I'm sure you have.\p"
    .string "Please, take this!$"

VermilionCity_PokemonCenter_1F_Text_UseDeviceForRematches::
    .string "When TRAINERS are ready for a\n"
    .string "rematch they will appear with a\l"
    .string "REMATCH ICON above their head.\p"
    .string "The COLOR of the ICON indicates\n"
    .string "how experienced you have to be\l"
    .string "to rebattle them.$"

VermilionCity_PokemonCenter_1F_Text_ExplainRedRematchIcon::
    .string "A RED REMATCH ICON indicates a\n"
    .string "REGULAR REMATCH.$"

VermilionCity_PokemonCenter_1F_Text_ExplainGreenRematchIcon::
    .string "A GREEN REMATCH ICON indicates a\n"
    .string "REMATCH AFTER REACHING CELADON\l"
    .string "CITY.$"

VermilionCity_PokemonCenter_1F_Text_ExplainPinkRematchIcon::
    .string "A PINK REMATCH ICON indicates a\n"
    .string "REMATCH AFTER REACHING FUCHSIA\l"
    .string "CITY.$"

VermilionCity_PokemonCenter_1F_Text_ExplainPurpleRematchIcon::
    .string "A PURPLE REMATCH ICON indicates a\n"
    .string "REMATCH AFTER OVERCOMING A GREAT\l"
    .string "CHALLENGE.$"

VermilionCity_PokemonCenter_1F_Text_ExplainBlueRematchIcon::
    .string "A BLUE REMATCH ICON indicates a\n"
    .string "REMATCH OF THE HIGHEST LEVEL.$"

VermilionCity_PokemonCenter_1F_Text_TurnOffRematchIconsInOptionMenu::
    .string "To turn off the icons go into\n"
    .string "the OPTION MENU and set REMATCH\l"
    .string "ICONS to OFF.$"

VermilionCity_PokemonCenter_1F_Text_ChargeTheVsSeekerByWalking::
    .string "The VS SEEKER charges automatically\n"
    .string "by walking around.\p"
    .string "Take 100 steps to fully charge it.$"

VermilionCity_PokemonCenter_1F_Text_ExplainVSSeeker::
    .string "How do you use the VS SEEKER?\n"
    .string "There's nothing to it.\p"
    .string "TRAINERS will appear with different\n"
    .string "COLORED REMATCH ICONS if the\l"
    .string "VS SEEKER is sufficiently charged.\p"
    .string "Simply USE the VS SEEKER in range\n"
    .string "of them and initiate the rematch.$"
