CeruleanCity_House4_Text_NothingEntertaining::
    .string "Sigh…\n"
    .string "Too much time, too little to do…\p"
    .string "Is nothing entertaining happening\n"
    .string "anywhere?$"

CeruleanCity_House4_Text_NewNewsInformativeHaveThis::
    .string "Ah!\n"
    .string "A new news report!\p"
    .string "Hmm…\p"
    .string "I see!\n"
    .string "That was quite informative!\p"
    .string "I applaud you for taking interest\n"
    .string "in the news at your young age.\p"
    .string "As my thanks for sharing the news\n"
    .string "with me, I want you to have this.$"

CeruleanCity_House4_Text_IncredibleNewsHaveBerries::
    .string "Oh, oh!\n"
    .string "Th-this news report!\p"
    .string "Hmm…\p"
    .string "Amazing!\n"
    .string "What an incredible piece of news!\p"
    .string "I haven't seen a news story this\n"
    .string "incredible in too long a time!\p"
    .string "Thanks for sharing this fantastic\n"
    .string "news. Have a bunch of BERRIES!$"

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers::
    .string "It seems such a shame to not share\n"
    .string "this news with other folks…\p"
    .string "I wish I could tell someone…\n"
    .string "Let others know the news…$"

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis::
    .string "Ah, you've spread the news for me?\p"
    .string "Good news becomes worthwhile when\n"
    .string "all sorts of people share it.\p"
    .string "As my thanks for your spreading\n"
    .string "the news, take this!$"

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries::
    .string "You've spread the news some more?\n"
    .string "Magnificent!\p"
    .string "That piece of news must be\n"
    .string "delighted to be passed around so.\p"
    .string "Yes, indeed!\p"
    .string "Consider this a show of\n"
    .string "appreciation from me and the news.\p"
    .string "I'll give you more BERRIES than\n"
    .string "I usually do.$"

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews::
    .string "I'm quite enjoying myself with all\n"
    .string "sorts of news.\p"
    .string "Yes, I am satisfied!\n"
    .string "I won't be bored for a while.$"

CeruleanCity_House4_Text_YourBerryPouchIsFull::
    .string "Hm? Your BERRY POUCH is full.\n"
    .string "My gift remains ungiven, then.$"

CeruleanCity_House4_Text_TeachMonMoveForMushroom::
    .string "I'm the POKéMON MOVE MANIAC.\p"
    .string "I know every single move that\n"
    .string "POKéMON learn growing up.\p"
    .string "I'm also a mushroom maniac.\p"
    .string "Bring me two TINYMUSHROOMS,\n"
    .string "or one BIG MUSHROOM.\p"
    .string "If you do that for me, I'll teach\n"
    .string "a move to one POKéMON.$"

CeruleanCity_House4_Text_WantMeToTeachMove::
    .string "Sniff, sniff…\n"
    .string "Hm! You smell of MUSHROOMS!\p"
    .string "Do you want me to teach a move\n"
    .string "to a POKéMON of yours?$"

CeruleanCity_House4_Text_TutorWhichMon::
    .string "Which POKéMON needs tutoring?$"

CeruleanCity_House4_Text_TeachWhichMove::
    .string "Which move should I teach?$"

CeruleanCity_House4_Text_NoMoveICanTeachThatMon::
    .string "Sorry…\p"
    .string "It doesn't appear as if I have a\n"
    .string "move I can teach that POKéMON.$"

CeruleanCity_House4_Text_IllNeedMushroomOrTwo::
    .string "Then, I'll need a MUSHROOM or two.\n"
    .string "What are you going to give me?$"

CeruleanCity_House4_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} handed over two\n"
    .string "TINYMUSHROOMS in exchange.$"

CeruleanCity_House4_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} handed over one\n"
    .string "BIG MUSHROOM in exchange.$"

CeruleanCity_House4_Text_NeedMushroomOrTwoToLearnMove::
    .string "If your POKéMON need to learn a\n"
    .string "move, I need a MUSHROOM or two.$"

CeruleanCity_House4_Text_CantTeachAnEgg::
    .string "Hunh? There isn't a single move\n"
    .string "that I can teach an EGG.$"
