Route2_Text_RouteSign::
    .string "ROUTE 2\n"
    .string "VIRIDIAN CITY - PEWTER CITY$"

Route2_Text_DiglettsCave::
    .string "DIGLETT'S CAVE$"

Route2_Text_BugsyAsksForNet::
    .string "BUGSY: Hey, did you find\n"
    .string "my NET yet?$"

Route2_Text_BugsyNetNotInInventory::
    .string "Please keep looking for it.\n"
    .string "It has to be somewhere.$"

Route2_Text_BugsyNetInInventory::
    .string "That's it!\n"
    .string "You found my NET!\p"
    .string "Thank you so much, now I can\n"
    .string "finally expand my team.\p"
    .string "As promised, I have something\n"
    .string "that might be useful to you.$"

Route2_Text_ExplainRepel::
    .string "Press R to toggle the REPEL ON\n"
    .string "and OFF.$"

Route2_Text_BugsyHasGivenRepel::
    .string "This is a REPEL. It keeps POKéMON\n"
    .string "away when you're walking through\p"
    .string "tall grass. It should make your\n"
    .string "journey a lot more tolerable.\p"
    .string "I'm a BUG type GYM LEADER, but even\n"
    .string "I get sick of those pesky insects.$"

Route2_Text_BugsySaysGoodbye::
    .string "Well now that you're prepared to\n"
    .string "travel, you should visit Johto when\p"
    .string "you get the chance. It's just WEST\n"
    .string "of the Kanto region.\p"
    .string "It's very beautiful and there are\n"
    .string "strong trainers there.\p"
    .string "If you visit my GYM I'll give you \n"
    .string "that battle I promised you earlier.\p"
    .string "Good luck on your adventure.\n"
    .string "I'll see you around.$"

Route2_Text_MaxIntro::
    .string "I've never won a battle before.$"

Route2_Text_MaxDefeat::
    .string "You're not even that good...$"

Route2_Text_MaxPostBattle::
    .string "My ZIGZAGOON picks up useful items\n"
    .string "for me.$"
